### ISSUE TITLE
The powder is also not working with max Great Explorer but works without

### ISSUE THREAD

**Issue by Mininoob46** [btwonion/skylper#18]

**Comment by Mininoob46** [comment]
it update the powder but not the chests
![image](https://github.com/btwonion/skylper/assets/64793464/69e872ad-78a1-414c-b513-8e03c616c11c)
![image](https://github.com/btwonion/skylper/assets/64793464/dde2ffa7-ed30-44a7-a7f5-8016ae0b7226)
so it does not detect the chests with max great explorer
i got the display by Disabled Great Explorer

**Comment by btwonion** [comment]
ah yeah. can you quickly show me how an opened chest looks like in the chat?
like the first messages after clicking the chest, including the drops.
then i can modify the existing message checks to match the ones with efficient miner, too.

**Comment by Mininoob46** [comment]
![image](https://github.com/btwonion/skylper/assets/64793464/6edf6b89-786d-49c4-8940-e44b4f0f3959)

**Comment by btwonion** [comment]
alright thanks

**Comment by Mininoob46** [comment]
&aYou uncovered a treasure chest!&#FFFF55 &8(&7x&#FFFF552&8)

**Comment by btwonion** [comment]
this bug should be fixed. i couldn't test it, but it *should* work correctly
