### ISSUE TITLE
Powder Grinding does not apper with max great explorer

### ISSUE THREAD

**Issue by Mininoob46** [btwonion/skylper#19]
it only appers when you do not have max greate explorer but it updates when you have max greate explorer

**Comment by btwonion** [comment]
thanks for the report. i found the error. should be fixed by the end of the day

**Comment by btwonion** [comment]
the bug should be fixed, but i am not able to test it atm. i would like to get some feedback on this

**Comment by Mininoob46** [comment]
works now but on the first chest it is 0 when it should be 1

**Comment by Mininoob46** [comment]
also the i open two chests and only go up by 1

**Comment by btwonion** [comment]
okay. can you test it with the mod of this run? https://github.com/btwonion/skylper/actions/runs/9066425281

**Comment by Mininoob46** [comment]
Works now

**Comment by btwonion** [comment]
great. feel free to submit errors and improvements!

**Comment by Mininoob46** [comment]
can you release this patch (the commit before the lates is released)

**Comment by btwonion** [comment]
beta 18 is out
