### ISSUE TITLE
powder grinding timer does not reset after changing lobbys 

### ISSUE THREAD

**Issue by Mininoob46** [btwonion/skylper#20]
![2024-05-26_21 10 07](https://github.com/btwonion/skylper/assets/64793464/01093c59-af6f-44b5-8aa6-dc153378da02)
![2024-05-26_21 10 25](https://github.com/btwonion/skylper/assets/64793464/79920a26-8b5f-4726-b1eb-e35597461cbe)

**Comment by btwonion** [comment]
hi,
thanks for the report. 
Currently the tracker is only resetted after 5 minutes of inactivity.
If you want me to change this behaviour let me know.

**Comment by Mininoob46** [comment]
No. There is more that the power resets and not the timer. So of you make it so the power only resets after 5 minutes. It also messes with the calculation

**Comment by btwonion** [comment]
good to know. i will fix this in the coming days

**Comment by btwonion** [comment]
fixed in this commit: 63b3213
release will come later today (or tomorrow)
