### ISSUE TITLE
waypoints text is facing the wrong way

### ISSUE THREAD

**Issue by Mininoob46** [btwonion/skylper#21]
![2024-05-26_10 25 58](https://github.com/btwonion/skylper/assets/64793464/e6d63780-ec30-46ff-9153-abd4dd93a260)
![2024-05-26_09 38 12](https://github.com/btwonion/skylper/assets/64793464/6d433e3f-31ee-4753-a8f7-d6d0868fac64)
version 1.20.6

**Comment by btwonion** [comment]
yo,
i actually thought i fixed this. 
Thanks for the report.

**Comment by btwonion** [comment]
got it finally fixed in 5d408e039372d4aaa404ad0b5743cc41c73c73a9 .
Nevertheless, I will leave this open until I added, that the waypoints don't shrink until they're nearly invisible.

**Comment by btwonion** [comment]
wasn't able to implement it now, but as long as waypoints are limited to the Crystal Hollows, this won't be a problem.
