### ISSUE TITLE
overlays are on always displaying

### ISSUE THREAD

**Issue by Mininoob46** [btwonion/skylper#22]
don't know why but sometimes the overlays are not displaying (ch)
restart does not work

**Comment by Mininoob46** [comment]
some restarts work

**Comment by btwonion** [comment]
are only specific overlays not displaying or is it every overlay?

**Comment by Mininoob46** [comment]
It is every ch overlay. But It is only sometimes it happens. It works right now.

**Comment by btwonion** [comment]
I was not able to replicate this error. i will close this for now.
If you experience this error again let me know!
