### ISSUE TITLE
cn waypoint is of center

### ISSUE THREAD

**Issue by Mininoob46** [btwonion/skylper#23]
![2024-05-29_21 49 01](https://github.com/btwonion/skylper/assets/64793464/927df44a-421c-4f12-b663-a146486645fa)

**Comment by btwonion** [comment]
i will take a look at it. rendering overall needs a rework...

**Comment by btwonion** [comment]
yeah this is awkward. 
![image](https://github.com/btwonion/skylper/assets/79146501/c8a72d75-a6ab-406a-a4db-8cff00126041)

**Comment by btwonion** [comment]
fixed with 4e45470
